version: '3.8'

services:
  ftp:
    image: fauria/vsftpd
    container_name: ftp-server
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      - FTP_USER=user
      - FTP_PASS=12345
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - PASV_ADDRESS=127.0.0.1
    volumes:
      - ./ftpdata:/home/vsftpd
    restart: unless-stopped
